# Dockerfile.express
FROM python:3.12-slim

# ตั้ง working directory
WORKDIR /usr/src/app

ENV PYTHONPATH=/usr/src/app/model

COPY model/ /usr/src/app/model/

# คัดลอกไฟล์ requirements
COPY ./requirements.txt .

# ติดตั้ง dependencies
RUN pip install --no-cache-dir -r requirements.txt

# คัดลอกโค้ดทั้งหมดของ backend เข้า container
COPY ./src ./src
# expose port สำหรับ API
EXPOSE 5001

# รัน backend service
CMD ["python", "src/services/prediction_service.py"]
